events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # ── Landing page ──────────────────────────────────────────────────────────
    server {
        listen 80;
        server_name centralauth.local;
        root /var/www/app;
        index index.html;
    }

    # ── Auth ──────────────────────────────────────────────────────────────────
    server {
        listen 80;
        server_name auth.centralauth.local;
        root /var/www/auth;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    server {
        listen 80;
        server_name api.auth.centralauth.local;
        location / {
            proxy_pass         http://auth-service:4000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_redirect     off;
        }
    }

    # ── Analytics ─────────────────────────────────────────────────────────────
    server {
        listen 80;
        server_name analytics.centralauth.local;
        root /var/www/analytics;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    server {
        listen 80;
        server_name api.analytics.centralauth.local;
        location / {
            proxy_pass         http://analytics-service:4002;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_redirect     off;
        }
    }

    # ── Report ────────────────────────────────────────────────────────────────
    server {
        listen 80;
        server_name report.centralauth.local;
        root /var/www/report;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    server {
        listen 80;
        server_name api.report.centralauth.local;
        location / {
            proxy_pass         http://report-service:4001;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_redirect     off;
        }
    }

    # ── Transaction ───────────────────────────────────────────────────────────
    server {
        listen 80;
        server_name transaction.centralauth.local;
        root /var/www/transaction;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    server {
        listen 80;
        server_name api.transaction.centralauth.local;
        location / {
            proxy_pass         http://transaction-service:4003;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_redirect     off;
        }
    }
}
